<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 oldsmobile_cutlass_supreme_sedan_71.glb --transform
Author: Barbo (https://sketchfab.com/barbo-autos)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oldsmobile-cutlass-supreme-sedan-71-78f76d386a4341b0b71745bdc50fd5ab
Title: Oldsmobile Cutlass Supreme Sedan '71
-->

<script lang="ts">
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	import * as BufferGeometryUtils from 'three/examples/jsm/utils/BufferGeometryUtils.js';
	import InteractiveGlint from './InteractiveGlint.svelte';

	const gltf = useGltf('/oldsmobile_cutlass_supreme_sedan_71-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} castShadow>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0.58}>
			<T.Group rotation={[Math.PI / 2, 0, 0]}>
				<T.Group position={[0, -0.47, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
					<T.Mesh
						geometry={gltf.nodes.chrome_M_Chrome_0.geometry}
						material={gltf.materials.M_Chrome}
					/>
					<T.Mesh
						geometry={gltf.nodes.chrome_M_Black_0.geometry}
						material={gltf.materials.M_Black}
					/>
				</T.Group>
				<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
					<InteractiveGlint geometry={gltf.nodes.body_M_Paint_0.geometry}>
						<slot />
					</InteractiveGlint>
					<!-- <T.Mesh
						geometry={gltf.nodes.body_M_Paint_0.geometry}
						on:create={({ ref }) => {
							// ref.geometry.computeVertexNormals();
							ref.geometry.computeTangents();
						}}
					>
						
					</T.Mesh> -->
					<T.Mesh geometry={gltf.nodes.body_M_Black_0.geometry} material={gltf.materials.M_Black} />
				</T.Group>
				<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
					<T.Mesh
						geometry={gltf.nodes.trim2_M_Badge_0.geometry}
						material={gltf.materials.M_Badge}
					/>
					<T.Mesh
						geometry={gltf.nodes.trim2_M_Lights_0.geometry}
						material={gltf.materials.M_Lights}
					/>
				</T.Group>
				<T.Mesh
					geometry={gltf.nodes['rear-view_M_Chrome_0'].geometry}
					material={gltf.materials.M_Chrome}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.door_handle_M_Chrome_0.geometry}
					material={gltf.materials.M_Chrome}
					rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
					scale={[-4.28, 4.28, 4.28]}
				/>
				<T.Mesh
					geometry={gltf.nodes.badges_2_M_Badge_0.geometry}
					material={gltf.materials.M_Badge}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.badges_M_Badge_0.geometry}
					material={gltf.materials.M_Badge}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.Circle002_M_Badge_0.geometry}
					material={gltf.materials.M_Badge}
					position={[0, -33.71, 80.73]}
					scale={3.01}
				/>
				<T.Mesh
					geometry={gltf.nodes['lights-glass_M_Lights_0'].geometry}
					material={gltf.materials.M_Lights}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.trim_M_Badge_0.geometry}
					material={gltf.materials.M_Badge}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.glass_M_Glass_0.geometry}
					material={gltf.materials.M_Glass}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.black2_M_Black_0.geometry}
					material={gltf.materials.M_Black}
					position={[0, 0.26, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.black_M_Black_0.geometry}
					material={gltf.materials.M_Black}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.glass2_M_Glass_0.geometry}
					material={gltf.materials.M_Glass}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.wheels_M_Wheel_0.geometry}
					material={gltf.materials.M_Wheel}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.badge3_M_Badge_0.geometry}
					material={gltf.materials.M_Badge}
					position={[-1.31, 2.03, 405.29]}
					scale={3.05}
				/>
				<T.Mesh
					geometry={gltf.nodes.lights_M_Lights_0.geometry}
					material={gltf.materials.M_Lights}
					position={[0, -0.47, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>

				<T.Mesh
					geometry={gltf.nodes.screws_M_Badge_0.geometry}
					material={gltf.materials.M_Badge}
					rotation={[Math.PI, 0, Math.PI]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes['plate-holder_M_Badge_0'].geometry}
					material={gltf.materials.M_Badge}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					geometry={gltf.nodes.plate_M_License_0.geometry}
					material={gltf.materials.M_License}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
