<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 scene.gltf --transform
Author: Gesy (https://sketchfab.com/mrgesy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dodge-challenger-2c1f18d2f0214cb7a746fc5dd2baeebe
Title: Dodge CHALLENGER
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/scene-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials.Material__295} />
      <T.Mesh geometry={gltf.nodes.Object_3.geometry} material={gltf.materials.Material__303} />
      <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.Material__304} />
      <T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.wire_225198087} />
      <T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials['01___Default']} />
      <T.Mesh geometry={gltf.nodes.Object_7.geometry} material={gltf.materials['01___Default']} />
      <T.Mesh geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.Material__287} />
      <T.Mesh geometry={gltf.nodes.Object_9.geometry} material={gltf.materials.Material__287} />
      <T.Mesh geometry={gltf.nodes.Object_10.geometry} material={gltf.materials.Material__287} />
      <T.Mesh geometry={gltf.nodes.Object_11.geometry} material={gltf.materials.Material__287} />
      <T.Mesh geometry={gltf.nodes.Object_12.geometry} material={gltf.materials.Material__287} />
      <T.Mesh geometry={gltf.nodes.Object_13.geometry} material={gltf.materials.Material__288} />
      <T.Mesh geometry={gltf.nodes.Object_14.geometry} material={gltf.materials.Material__289} />
      <T.Mesh geometry={gltf.nodes.Object_15.geometry} material={gltf.materials.Material__289} />
      <T.Mesh geometry={gltf.nodes.Object_16.geometry} material={gltf.materials.Material__289} />
      <T.Mesh geometry={gltf.nodes.Object_17.geometry} material={gltf.materials.Material__289} />
      <T.Mesh geometry={gltf.nodes.Object_18.geometry} material={gltf.materials.Material__289} />
      <T.Mesh geometry={gltf.nodes.Object_19.geometry} material={gltf.materials.Material__289} />
      <T.Mesh geometry={gltf.nodes.Object_20.geometry} material={gltf.materials.Material__289} />
      <T.Mesh geometry={gltf.nodes.Object_21.geometry} material={gltf.materials.Material__289} />
      <T.Mesh geometry={gltf.nodes.Object_22.geometry} material={gltf.materials.Material__289} />
      <T.Mesh geometry={gltf.nodes.Object_23.geometry} material={gltf.materials.Material__290} />
      <T.Mesh geometry={gltf.nodes.Object_24.geometry} material={gltf.materials.Material__290} />
      <T.Mesh geometry={gltf.nodes.Object_25.geometry} material={gltf.materials.Material__290} />
      <T.Mesh geometry={gltf.nodes.Object_26.geometry} material={gltf.materials.Material__291} />
      <T.Mesh geometry={gltf.nodes.Object_27.geometry} material={gltf.materials.Material__291} />
      <T.Mesh geometry={gltf.nodes.Object_28.geometry} material={gltf.materials.Material__291} />
      <T.Mesh geometry={gltf.nodes.Object_29.geometry} material={gltf.materials.Material__291} />
      <T.Mesh geometry={gltf.nodes.Object_30.geometry} material={gltf.materials.Material__291} />
      <T.Mesh geometry={gltf.nodes.Object_31.geometry} material={gltf.materials.Material__296} />
      <T.Mesh geometry={gltf.nodes.Object_32.geometry} material={gltf.materials.Material__296} />
      <T.Mesh geometry={gltf.nodes.Object_33.geometry} material={gltf.materials.Material__296} />
      <T.Mesh geometry={gltf.nodes.Object_34.geometry} material={gltf.materials.Material__297} />
      <T.Mesh geometry={gltf.nodes.Object_35.geometry} material={gltf.materials.Material__297} />
      <T.Mesh geometry={gltf.nodes.Object_36.geometry} material={gltf.materials.Material__298} />
      <T.Mesh geometry={gltf.nodes.Object_37.geometry} material={gltf.materials.Material__298} />
      <T.Mesh geometry={gltf.nodes.Object_38.geometry} material={gltf.materials.Material__299} />
      <T.Mesh geometry={gltf.nodes.Object_39.geometry} material={gltf.materials.Material__300} />
      <T.Mesh geometry={gltf.nodes.Object_40.geometry} material={gltf.materials.Material__300} />
      <T.Mesh geometry={gltf.nodes.Object_41.geometry} material={gltf.materials.Material__301} />
      <T.Mesh geometry={gltf.nodes.Object_42.geometry} material={gltf.materials.Material__301} />
      <T.Mesh geometry={gltf.nodes.Object_43.geometry} material={gltf.materials.Material__301} />
      <T.Mesh geometry={gltf.nodes.Object_44.geometry} material={gltf.materials.Material__301} />
      <T.Mesh geometry={gltf.nodes.Object_45.geometry} material={gltf.materials.Material__301} />
      <T.Mesh geometry={gltf.nodes.Object_46.geometry} material={gltf.materials.Material__301} />
      <T.Mesh geometry={gltf.nodes.Object_47.geometry} material={gltf.materials.Material__301} />
      <T.Mesh geometry={gltf.nodes.Object_48.geometry} material={gltf.materials.Material__301} />
      <T.Mesh geometry={gltf.nodes.Object_49.geometry} material={gltf.materials.Material__301} />
      <T.Mesh geometry={gltf.nodes.Object_50.geometry} material={gltf.materials.Material__301} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
